### PR TITLE
The latest version is not supported the Python 3.7

### PR DESCRIPTION
**Pull request by olivebian**
The latest version is not supported the Python 3.7,
Because of the upgrade for the incident detection for Python, we also should upgrade the pmmif library

### CODE REVIEW

**Comment by hemster** [comment]
Hi @njr0 , could you please review this PR? We are Libra squad from Skyscanner and we own PQS now. This fix the dependency issue that we are facing right now (Python 3.7 migration). Thanks!

**Comment by njr0** [comment]
Is there a reason you've pinned the version of pandas to 1.3.2? I generally think it's very unhelpful to pin version rather than use >= unless something is known to break with a later version.

**Comment by olivebian** [comment]
Updated, could you help review again? Many thanks!

**Comment by njr0** [comment]
Hi. Thanks for the change and for proposing the larger change. To be clear, I'm quite happy to accept a merge, but I need to understand it, and I don't yet. When you say "the latest version is not supported the Python 3.7", what you do you mean? I've run both the pmmif and the tdda tests in python 3.7.3 and python 3.9, and everything works. It also doesn't look as if your changes are things that would be likely to be affected by the Python version.

Could you provide a trivial example of something that works in an older Python version (presumably 3.6) and does not work under 3.7? Or even, just of something that doesn't work under 3.7?

It looks to me like it's more likely to be something to do with library versions (probably pandas), rather than the Python version. Of course, it could really be the Python version, but as I say, at least the TDDA and PMMIF tests work for me under 3.7.

Thanks

Nick

**Comment by olivebian** [comment]
https://pypi.org/project/feather-format/ 
We need to import the feather library，this depends on the above feather-format library, but the newest feather-format library only supports python under 3.5, I don't know if my pr is a good solution.

**Comment by njr0** [comment]
But it works under Python 3.7 (and, indeed, 3.9), right? You just mean they haven't tagged it as working with 3.7? Is that right? Or do you actually have code that won't run under 3.7?

**Comment by olivebian** [comment]
Yes, I had imported the latest library feather-format in our pqs-incident-detection project, but it doesn't support python version 3.5 or Later.

**Comment by njr0** [comment]
Hi. I'm sorry, but I cannot produce an error with Python 3.7. I have just run this with the current pmmif, feather-format and TDDA on python 3.7.6. I have also run on python 3.9 without problems:

    $ python3 --version
    Python 3.7.6

    $ python3
    Python 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) 
    [Clang 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import feather
    >>> feather.__version__
    '0.4.1'
    >>> ^D
    
    $ python3 testtdda.py
    Skipping Postgres tests (no driver library)
    Skipping MySQL tests (no driver library)
    .....................................................................................ssssssssss..................................................................sssss.............................
    ----------------------------------------------------------------------
    Ran 195 tests in 17.747s
    
    OK (skipped=15)
    
    $ cd ../../pmmif/pmmif/
    
    $ python3 testpmm.py
    ...
    ----------------------------------------------------------------------
    Ran 3 tests in 0.008s
    
    OK

Could you provide a short code snippet of something with pmmif that works in Python 3.5 and not in Python 3.7 if that is what you believe is not working? Thanks.

**Comment by olivebian** [comment]
So sorry,@njr0, I tried to use the latest pmmif version and import the latest feather-format library under python 3.7 last week, it seems working as you said. I don't know why, the last error was "Feather-format is not available".
However, the problem was solved, I will close this pr, many thanks!

**Comment by njr0** [comment]
That's great news. Thanks.

**Pull request closed without merging**
